// Alias: përdor Jenkinsfile në root të repo (ProjektCloud/Jenkinsfile)
// Ky skedar mbetet për referencë; job-i Jenkins duhet të përdorë Script Path: Jenkinsfile

pipeline {
    agent any

    tools {
        jdk 'JDK-17'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'chmod +x mvnw && ./mvnw clean install'
                    } else {
                        bat 'mvnw.cmd clean install'
                    }
                }
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Archive JAR') {
            steps {
                archiveArtifacts artifacts: 'web/target/*.jar', fingerprint: true, onlyIfSuccessful: true
            }
        }
    }
}
